import { Component, OnInit } from '@angular/core';
import { FilterMatchMode, PrimeNGConfig } from 'primeng/api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  ptBrConfigs = {
    after: 'Depois',
    accept: 'Sim',
    addRule: 'Adicionar regra',
    am: 'AM',
    apply: 'Aplicar',
    before: 'Antes',
    cancel: 'Cancelar',
    choose: 'Escolher',
    chooseDate: 'Escolher data',
    chooseMonth: 'Escolher mês',
    chooseYear: 'Escolher ano',
    clear: 'Limpar',
    contains: 'Contém',
    dateAfter: 'Data depois de',
    dateBefore: 'Data antes de',
    dateFormat: 'dd/mm/y',
    dateIs: 'Data é',
    dateIsNot: 'Data não é',
    dayNames: [
      'Domingo',
      'Segunda',
      'Terça',
      'Quarta',
      'Quinta',
      'Sexta',
      'Sábado',
    ],
    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
    emptyFilterMessage: 'Nenhum resultado encontrado',
    emptyMessage: 'Nenhuma opção disponível',
    emptySearchMessage: 'Nenhum resultado encontrado',
    emptySelectionMessage: 'Nenhum item selecionado',
    endsWith: 'Termina com',
    equals: 'Igual',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    firstDayOfWeek: 0,
    gt: 'Maior que',
    gte: 'Maior ou igual a',
    lt: 'Menor que',
    lte: 'Menor ou igual a',
    matchAll: 'Corresponder todos',
    matchAny: 'Corrresponder qualquer',
    medium: 'Médio',
    monthNames: [
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro',
    ],
    monthNamesShort: [
      'Jan',
      'Fev',
      'Mar',
      'Abr',
      'Mai',
      'Jun',
      'Jul',
      'Ago',
      'Set',
      'Out',
      'Nov',
      'Dez',
    ],
    nextDecade: 'Próxima Década',
    nextHour: 'Próxima Hora',
    nextMinute: 'Próximo Minuto',
    nextMonth: 'Próximo Mês',
    nextSecond: 'Próximo Segundo',
    nextYear: 'Próximo Ano',
    noFilter: 'Sem Filtro',
    notContains: 'Não contém',
    notEquals: 'Diferente',
    passwordPrompt: 'Digite uma senha',
    pending: 'Pendente',
    pm: 'PM',
    prevDecade: 'Década anterior',
    prevHour: 'Hora anterior',
    prevMinute: 'Minuto anterior',
    prevMonth: 'Mês anterior',
    prevSecond: 'Segundo anterior',
    prevYear: 'Ano anterior',
    reject: 'Não',
    removeRule: 'Remover regra',
    searchMessage: 'Exisem {0} resultados disponíveis',
    selectionMessage: '{0} itens selecionados',
    startsWith: 'Começa com',
    strong: 'Forte',
    today: 'Hoje',
    upload: 'Enviar',
    weak: 'Fraco',
    weekHeader: 'Sem',
    aria: {
      cancelEdit: 'Cancelar Edição',
      close: 'Fechar',
      collapseRow: 'Recolher Linha',
      editRow: 'Editar Linha',
      expandRow: 'Expandir Linha',
      falseLabel: 'Falso',
      filterConstraint: 'Restrição de Filtro',
      filterOperator: 'Operador de Filtro',
      firstPageLabel: 'Primeira Página',
      gridView: 'Visualização de Grade',
      hideFilterMenu: 'Esconder Menu de Filtro',
      jumpToPageDropdownLabel: 'Ir para a Página',
      jumpToPageInputLabel: 'Ir para a Página',
      lastPageLabel: 'Última Página',
      listView: 'Visualização de Lista',
      moveAllToSource: 'Mover Todos para a Origem',
      moveAllToTarget: 'Mover Todos para o Destino',
      moveBottom: 'Mover para o Final',
      moveDown: 'Mover para Baixo',
      moveTop: 'Mover para o Topo',
      moveToSource: 'Mover para a Origem',
      moveToTarget: 'Mover para o Destino',
      moveUp: 'Mover para Cima',
      navigation: 'Navegação',
      next: 'Próximo',
      nextPageLabel: 'Próxima Página',
      nullLabel: 'Não Selecionado',
      pageLabel: 'Página {page}',
      previous: 'Anterior',
      previousPageLabel: 'Página Anterior',
      rotateLeft: 'Rotacionar para a Esquerda',
      rotateRight: 'Rotacionar para a Direita',
      rowsPerPageLabel: 'Linhas por página',
      saveEdit: 'Salvar Edição',
      scrollTop: 'Rolar para o Topo',
      selectAll: 'Todos os itens selecionados',
      selectRow: 'Linha Selecionada',
      showFilterMenu: 'Mostrar Menu de Filtro',
      slide: 'Deslizar',
      slideNumber: 'Slide {slideNumber}',
      star: '1 estrela',
      stars: '{star} estrelas',
      trueLabel: 'Verdadeiro',
      unselectAll: 'Todos os itens desmarcados',
      unselectRow: 'Linha Desmarcada',
      zoomImage: 'Ampliar Imagem',
      zoomIn: 'Ampliar',
      zoomOut: 'Reduzir',
    },
  };

  constructor(private primengConfig: PrimeNGConfig) {}

  ngOnInit(): void {
    this.primengConfig.setTranslation(this.ptBrConfigs);

    this.primengConfig.filterMatchModeOptions = {
      text: [
        FilterMatchMode.STARTS_WITH,
        FilterMatchMode.CONTAINS,
        FilterMatchMode.NOT_CONTAINS,
        FilterMatchMode.ENDS_WITH,
        FilterMatchMode.EQUALS,
        FilterMatchMode.NOT_EQUALS,
      ],
      numeric: [
        FilterMatchMode.EQUALS,
        FilterMatchMode.NOT_EQUALS,
        FilterMatchMode.LESS_THAN,
        FilterMatchMode.LESS_THAN_OR_EQUAL_TO,
        FilterMatchMode.GREATER_THAN,
        FilterMatchMode.GREATER_THAN_OR_EQUAL_TO,
      ],
      date: [
        FilterMatchMode.DATE_IS,
        FilterMatchMode.DATE_IS_NOT,
        FilterMatchMode.DATE_BEFORE,
        FilterMatchMode.DATE_AFTER,
      ],
    };

    this.primengConfig.ripple = true;
  }
}
